services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:changeme", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 30

  eureka-server:
    build: ./eureka-server
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    depends_on:
      - elasticsearch

  api-gateway:
    build: ./api-gateway
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy

  search-service:
    build: ./search-service
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
