server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/api/**
          # Si desea quitar el prefijo /api antes de llegar al microservicio:
          # filters:
          #   - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
            allowedMethods: [GET, POST, OPTIONS]
            allowedHeaders: ["*"]
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
