server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTIC_URL:http://localhost:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:changeme}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
